(require 'magit)
(autoload 'mo-git-blame-file "mo-git-blame" nil t)
(autoload 'mo-git-blame-current "mo-git-blame" nil t)
(set-face-foreground 'magit-diff-add "Green")
(set-face-foreground 'magit-diff-del "Red")
(set-face-background 'magit-item-highlight "SkyBlue")
